export interface Comparatif {
  slug: string;
  title: string;
  metaTitle: string;
  metaDescription: string;
  option1: { name: string; pros: string[]; cons: string[]; avgPrice: string };
  option2: { name: string; pros: string[]; cons: string[]; avgPrice: string };
  verdict: string;
  relatedServiceSlug: string;
}

export const comparatifs: Comparatif[] = [
  {
    slug: "pompe-a-chaleur-vs-chaudiere-gaz",
    title: "Pompe a chaleur vs Chaudiere gaz",
    metaTitle:
      "Pompe a chaleur vs Chaudiere gaz : comparatif complet",
    metaDescription:
      "Pompe a chaleur ou chaudiere gaz ? Comparez les avantages, inconvenients et prix pour choisir le meilleur systeme de chauffage pour votre logement.",
    option1: {
      name: "Pompe a chaleur (PAC)",
      pros: [
        "Economies d'energie importantes (COP de 3 a 5)",
        "Eligible aux aides de l'Etat (MaPrimeRenov, CEE)",
        "Chauffage et climatisation en un seul appareil",
        "Energie renouvelable, faible empreinte carbone",
        "Duree de vie de 15 a 20 ans",
      ],
      cons: [
        "Cout d'installation eleve (8 000 a 15 000 EUR)",
        "Performances reduites par grand froid (PAC air/air)",
        "Nuisance sonore possible du groupe exterieur",
        "Entretien annuel obligatoire par un professionnel",
      ],
      avgPrice: "8 000 - 15 000 EUR",
    },
    option2: {
      name: "Chaudiere gaz a condensation",
      pros: [
        "Cout d'installation plus abordable",
        "Performances stables quelle que soit la temperature",
        "Technologie eprouvee et fiable",
        "Compatible avec les radiateurs existants",
        "Installation plus simple et rapide",
      ],
      cons: [
        "Energie fossile, prix du gaz volatil",
        "Interdiction dans les constructions neuves depuis 2022",
        "Empreinte carbone elevee",
        "Raccordement au reseau de gaz necessaire",
      ],
      avgPrice: "3 000 - 7 000 EUR",
    },
    verdict:
      "La pompe a chaleur est le choix le plus economique a long terme grace aux economies d'energie et aux aides financieres disponibles. Elle est particulierement adaptee aux logements bien isoles en climat tempere. La chaudiere gaz reste pertinente en remplacement sur un reseau existant ou dans les zones a hivers rigoureux, mais son avenir est limite par les nouvelles reglementations environnementales.",
    relatedServiceSlug: "entretien-pompe-chaleur",
  },
  {
    slug: "panneaux-solaires-autoconsommation-vs-revente",
    title: "Panneaux solaires : autoconsommation vs revente totale",
    metaTitle:
      "Panneaux solaires : autoconsommation ou revente totale ?",
    metaDescription:
      "Autoconsommation ou revente totale d'electricite solaire ? Comparez les deux options pour rentabiliser au mieux vos panneaux photovoltaiques.",
    option1: {
      name: "Autoconsommation avec revente du surplus",
      pros: [
        "Reduction directe de la facture d'electricite",
        "Prime a l'autoconsommation versee par EDF OA",
        "Revente du surplus a tarif garanti sur 20 ans",
        "Independance energetique partielle",
        "Valorisation en cas de hausse du prix de l'electricite",
      ],
      cons: [
        "Rentabilite dependante de votre profil de consommation",
        "Production et consommation pas toujours synchronisees",
        "Necessite d'adapter ses habitudes (consommer en journee)",
        "Cout d'une batterie de stockage eleve en option",
      ],
      avgPrice: "7 000 - 12 000 EUR (3 kWc)",
    },
    option2: {
      name: "Revente totale de la production",
      pros: [
        "Tarif d'achat garanti par EDF OA sur 20 ans",
        "Revenus reguliers et previsibles",
        "Pas besoin d'adapter sa consommation",
        "Rentabilite calculable a l'avance",
      ],
      cons: [
        "Tarif de revente en baisse ces dernieres annees",
        "Pas de reduction directe sur la facture d'electricite",
        "Pas de prime a l'autoconsommation",
        "Moins avantageux si le prix de l'electricite augmente",
        "Revenus soumis a fiscalite au-dela de 3 kWc",
      ],
      avgPrice: "7 000 - 12 000 EUR (3 kWc)",
    },
    verdict:
      "L'autoconsommation avec revente du surplus est aujourd'hui l'option la plus avantageuse pour la majorite des foyers. Elle permet de reduire sa facture d'electricite tout en beneficiant de la prime a l'autoconsommation et de la revente du surplus. La revente totale peut rester interessante pour des installations en toiture non orientee vers les pieces de vie ou pour des residences secondaires.",
    relatedServiceSlug: "nettoyage-panneaux-solaires",
  },
  {
    slug: "volet-roulant-electrique-vs-manuel",
    title: "Volet roulant electrique vs manuel",
    metaTitle:
      "Volet roulant electrique ou manuel : lequel choisir ?",
    metaDescription:
      "Volet roulant electrique ou manuel ? Comparez les prix, avantages et inconvenients pour faire le bon choix lors de votre installation ou remplacement.",
    option1: {
      name: "Volet roulant electrique",
      pros: [
        "Confort d'utilisation au quotidien (telecommande, interrupteur)",
        "Automatisation possible (programmation horaire, domotique)",
        "Ideal pour les fenetres difficiles d'acces",
        "Meilleure securite anti-intrusion",
        "Option solaire disponible (sans cablage electrique)",
      ],
      cons: [
        "Cout d'achat et d'installation plus eleve",
        "Reparation du moteur couteuse en cas de panne",
        "Necessite une alimentation electrique ou un panneau solaire",
        "Panne possible du moteur ou de la telecommande",
      ],
      avgPrice: "300 - 800 EUR par volet",
    },
    option2: {
      name: "Volet roulant manuel (sangle ou manivelle)",
      pros: [
        "Prix d'achat et d'installation reduit",
        "Aucune alimentation electrique necessaire",
        "Fonctionnement simple et fiable",
        "Entretien minimal et reparations peu couteuses",
        "Installation rapide",
      ],
      cons: [
        "Effort physique necessaire a chaque manipulation",
        "Pas de programmation ni d'automatisation possible",
        "Moins adapte aux grandes fenetres (poids du tablier)",
        "Usure plus rapide de la sangle",
      ],
      avgPrice: "100 - 350 EUR par volet",
    },
    verdict:
      "Le volet roulant electrique offre un confort superieur et des possibilites d'automatisation appreciables au quotidien. Il est particulierement recommande pour les grandes fenetres, les fenetres en hauteur ou pour les personnes a mobilite reduite. Le volet manuel reste un excellent choix pour les petits budgets ou les petites fenetres facilement accessibles.",
    relatedServiceSlug: "reparation-volets-roulants",
  },
  {
    slug: "ramonage-mecanique-vs-chimique",
    title: "Ramonage mecanique vs chimique",
    metaTitle:
      "Ramonage mecanique ou chimique : quelle methode choisir ?",
    metaDescription:
      "Ramonage mecanique ou chimique ? Comparez les deux methodes de ramonage de cheminee pour entretenir votre conduit en toute securite.",
    option1: {
      name: "Ramonage mecanique",
      pros: [
        "Seule methode reconnue legalement (certificat de ramonage)",
        "Nettoyage complet et en profondeur du conduit",
        "Permet de detecter d'eventuelles fissures ou defauts",
        "Obligatoire 1 a 2 fois par an selon les reglements",
        "Efficace sur tous types de depots (suie, goudron, bistre)",
      ],
      cons: [
        "Necessite l'intervention d'un professionnel certifie",
        "Peut generer un peu de poussiere dans l'habitation",
        "Prix plus eleve qu'un produit chimique",
        "Rendez-vous a planifier a l'avance",
      ],
      avgPrice: "50 - 120 EUR par intervention",
    },
    option2: {
      name: "Ramonage chimique (buche ou poudre)",
      pros: [
        "Facile a utiliser soi-meme",
        "Cout tres reduit",
        "Entretien complementaire entre deux ramonages",
        "Aide a decoller les depots de suie et de goudron",
      ],
      cons: [
        "Ne remplace PAS le ramonage mecanique obligatoire",
        "Ne delivre pas de certificat de ramonage",
        "Efficacite limitee sur les depots importants",
        "Non reconnu par les assurances en cas de sinistre",
        "Peut donner un faux sentiment de securite",
      ],
      avgPrice: "10 - 25 EUR par buche",
    },
    verdict:
      "Le ramonage mecanique est indispensable et obligatoire : c'est le seul qui delivre un certificat de ramonage valable aupres de votre assurance. Le ramonage chimique est un bon complement entre deux ramonages mecaniques, mais il ne peut en aucun cas le remplacer. Pour etre en conformite et en securite, faites appel a un ramoneur certifie au moins une fois par an.",
    relatedServiceSlug: "ramonage-cheminee",
  },
  {
    slug: "chauffe-eau-electrique-vs-thermodynamique",
    title: "Chauffe-eau electrique vs thermodynamique",
    metaTitle: "Chauffe-eau electrique ou thermodynamique : lequel choisir ?",
    metaDescription: "Chauffe-eau electrique ou thermodynamique ? Comparez les prix, la consommation et les aides pour choisir le meilleur ballon d'eau chaude.",
    option1: {
      name: "Chauffe-eau electrique (cumulus)",
      pros: [
        "Prix d'achat et d'installation reduit",
        "Installation simple et rapide",
        "Aucune contrainte d'emplacement",
        "Technologie fiable et eprouvee",
        "Entretien minimal (detartrage tous les 2-3 ans)",
      ],
      cons: [
        "Consommation electrique elevee",
        "Cout d'utilisation important (400-600 EUR/an)",
        "Non eligible aux aides financieres",
        "Empreinte carbone plus elevee",
      ],
      avgPrice: "500 - 1 500 EUR",
    },
    option2: {
      name: "Chauffe-eau thermodynamique",
      pros: [
        "Economies d'energie de 50 a 70%",
        "Eligible MaPrimeRenov et CEE",
        "Empreinte carbone reduite",
        "Cout d'utilisation faible (150-250 EUR/an)",
        "Duree de vie de 15 a 20 ans",
      ],
      cons: [
        "Cout d'achat 2 a 3 fois plus eleve",
        "Necessite un local non chauffe de 10 m3 minimum",
        "Bruit du compresseur (40-50 dB)",
        "Performances reduites sous 5 degres",
      ],
      avgPrice: "2 000 - 4 000 EUR",
    },
    verdict: "Le chauffe-eau thermodynamique est le choix le plus economique a long terme. Malgre un investissement initial plus eleve, les economies d'energie (200 a 400 EUR/an) et les aides financieres permettent un retour sur investissement en 3 a 5 ans. Le cumulus electrique reste pertinent pour les petits logements ou les budgets tres limites.",
    relatedServiceSlug: "installation-chauffe-eau",
  },
  {
    slug: "douche-italienne-vs-baignoire",
    title: "Douche italienne vs baignoire",
    metaTitle: "Douche italienne ou baignoire : que choisir pour votre salle de bain ?",
    metaDescription: "Douche italienne ou baignoire ? Comparez le confort, l'espace, la consommation d'eau et les prix pour amenager votre salle de bain.",
    option1: {
      name: "Douche italienne",
      pros: [
        "Gain de place dans la salle de bain",
        "Accessibilite PMR et personnes agees",
        "Consommation d'eau reduite (40-60 litres vs 150-200 litres)",
        "Esthetique moderne et valorisante",
        "Nettoyage facile",
      ],
      cons: [
        "Pas de bain possible pour la detente",
        "Installation technique (etancheite critique)",
        "Moins adapte aux familles avec jeunes enfants",
        "Risque de projection d'eau sans bonne paroi",
      ],
      avgPrice: "1 500 - 5 000 EUR",
    },
    option2: {
      name: "Baignoire",
      pros: [
        "Confort du bain pour la detente",
        "Ideale pour les familles avec enfants",
        "Large choix de modeles et tailles",
        "Option balneo disponible",
        "Peut servir de douche avec un pare-baignoire",
      ],
      cons: [
        "Encombrement important dans la salle de bain",
        "Consommation d'eau elevee (150-200 litres par bain)",
        "Acces difficile pour les personnes a mobilite reduite",
        "Entretien plus contraignant",
      ],
      avgPrice: "500 - 3 000 EUR",
    },
    verdict: "La douche italienne est le choix optimal pour les petites salles de bain, les personnes agees et ceux qui privilegient l'economie d'eau. La baignoire reste indispensable pour les familles avec jeunes enfants et les amateurs de bains relaxants. Si l'espace le permet, la combinaison des deux est la solution ideale.",
    relatedServiceSlug: "renovation-salle-de-bain",
  },
  {
    slug: "carrelage-vs-parquet",
    title: "Carrelage vs parquet",
    metaTitle: "Carrelage ou parquet : quel revetement de sol choisir ?",
    metaDescription: "Carrelage ou parquet ? Comparez la durabilite, l'entretien, le confort et les prix pour choisir le meilleur revetement de sol.",
    option1: {
      name: "Carrelage",
      pros: [
        "Tres resistant aux chocs, rayures et taches",
        "Impermeable, ideal pour pieces humides",
        "Entretien tres facile",
        "Duree de vie superieure a 30 ans",
        "Compatible plancher chauffant (excellente conductivite)",
      ],
      cons: [
        "Sensation de froid sous les pieds",
        "Pose technique necessitant un professionnel",
        "Bruit de pas et resonance acoustique",
        "Remplacement d'un carreau casse delicat",
      ],
      avgPrice: "30 - 120 EUR/m2 pose",
    },
    option2: {
      name: "Parquet (massif ou contrecolle)",
      pros: [
        "Chaleur et confort sous les pieds",
        "Esthetique noble et naturelle",
        "Isolation acoustique naturelle",
        "Renovable par poncage (parquet massif)",
        "Valorise le bien immobilier",
      ],
      cons: [
        "Sensible a l'eau et a l'humidite",
        "Entretien regulier necessaire (huile, vitrification)",
        "Rayures et marques d'usure visibles",
        "Prix plus eleve pour le massif",
      ],
      avgPrice: "30 - 150 EUR/m2 pose",
    },
    verdict: "Le carrelage s'impose dans les pieces humides (cuisine, salle de bain, entree) et les pieces a fort passage. Le parquet est preferable dans les chambres et le salon pour son confort et sa chaleur. Le carrelage imitation parquet est un bon compromis, offrant l'esthetique du bois avec la resistance du carrelage.",
    relatedServiceSlug: "pose-carrelage",
  },
  {
    slug: "vmc-simple-flux-vs-double-flux",
    title: "VMC simple flux vs double flux",
    metaTitle: "VMC simple flux ou double flux : quelle ventilation choisir ?",
    metaDescription: "VMC simple flux ou double flux ? Comparez les prix, les performances energetiques et le confort pour choisir la meilleure ventilation.",
    option1: {
      name: "VMC simple flux (hygroreglable)",
      pros: [
        "Prix d'achat et d'installation reduit",
        "Installation simple, peu de gaines",
        "Entretien facile et peu couteux",
        "Adaptee a la renovation",
        "Fonctionnement silencieux",
      ],
      cons: [
        "Deperditions de chaleur par l'air extrait",
        "Air entrant non filtre ni prechauffe",
        "Economies d'energie limitees",
        "Inconfort en hiver (air froid entrant)",
      ],
      avgPrice: "500 - 1 500 EUR",
    },
    option2: {
      name: "VMC double flux",
      pros: [
        "Recuperation de 80 a 90% de la chaleur",
        "Air entrant filtre (pollens, poussieres)",
        "Economies de chauffage de 15 a 25%",
        "Confort thermique superieur en hiver",
        "Eligible aux aides financieres",
      ],
      cons: [
        "Cout d'installation 3 a 5 fois plus eleve",
        "Installation complexe (double reseau de gaines)",
        "Entretien des filtres tous les 3 mois",
        "Encombrement du caisson echangeur",
      ],
      avgPrice: "4 000 - 8 000 EUR",
    },
    verdict: "La VMC double flux est le choix optimal pour les constructions neuves et les renovations lourdes de logements bien isoles. Elle se rentabilise en 8 a 12 ans grace aux economies de chauffage. La VMC simple flux hygroreglable type B reste le meilleur choix en renovation legere : elle offre un bon rapport cout-performance et s'installe facilement.",
    relatedServiceSlug: "installation-vmc",
  },
  {
    slug: "fenetre-pvc-vs-aluminium-vs-bois",
    title: "Fenetre PVC vs aluminium vs bois",
    metaTitle: "Fenetre PVC, aluminium ou bois : quel materiau choisir ?",
    metaDescription: "PVC, aluminium ou bois pour vos fenetres ? Comparez isolation, esthetique, prix et entretien des trois materiaux de menuiserie.",
    option1: {
      name: "Fenetre PVC",
      pros: [
        "Meilleur rapport qualite-prix du marche",
        "Excellente isolation thermique (Uw 1,2-1,6)",
        "Entretien quasi inexistant",
        "Bonne duree de vie (30-40 ans)",
        "Large choix de finitions modernes",
      ],
      cons: [
        "Profils plus epais, surface vitree reduite",
        "Aspect moins noble que le bois ou l'aluminium",
        "Deformation possible a haute temperature",
        "Recyclage encore imparfait",
      ],
      avgPrice: "200 - 500 EUR par fenetre",
    },
    option2: {
      name: "Fenetre aluminium",
      pros: [
        "Profils tres fins, maximum de lumiere",
        "Design moderne et elegant",
        "Toutes teintes RAL disponibles",
        "100% recyclable",
        "Tres longue duree de vie (40-50 ans)",
      ],
      cons: [
        "Prix 40 a 60% superieur au PVC",
        "Moins isolant sans rupture de pont thermique",
        "Risque de condensation sur profils non RPT",
        "Reparation plus complexe",
      ],
      avgPrice: "400 - 800 EUR par fenetre",
    },
    verdict: "Le PVC est le choix le plus judicieux pour la majorite des projets : il offre la meilleure isolation au meilleur prix. L'aluminium s'impose pour les grandes baies vitrees et les maisons contemporaines ou la finesse des profils est essentielle. Le bois (non detaille ici, 500-1000 EUR) reste le choix du patrimoine et des batiments anciens, mais necessite un entretien regulier.",
    relatedServiceSlug: "pose-fenetres",
  },
  {
    slug: "isolation-interieure-vs-exterieure",
    title: "Isolation interieure vs exterieure",
    metaTitle: "Isolation par l'interieur ou l'exterieur : que choisir ?",
    metaDescription: "Isolation interieure (ITI) ou exterieure (ITE) ? Comparez les performances, les prix et les contraintes pour bien isoler votre logement.",
    option1: {
      name: "Isolation par l'interieur (ITI)",
      pros: [
        "Cout 2 a 3 fois inferieur a l'ITE",
        "Pas de modification de l'aspect exterieur",
        "Travaux possibles piece par piece",
        "Pas d'echafaudage necessaire",
        "Compatible avec tous les types de facades",
      ],
      cons: [
        "Reduction de la surface habitable (3-5%)",
        "Ponts thermiques non traites (planchers, murs de refend)",
        "Travaux intrusifs (demenagement temporaire des pieces)",
        "Risque de condensation si mal realisee",
      ],
      avgPrice: "30 - 80 EUR/m2",
    },
    option2: {
      name: "Isolation par l'exterieur (ITE)",
      pros: [
        "Suppression de tous les ponts thermiques",
        "Aucune perte de surface habitable",
        "Pas de demenagement pendant les travaux",
        "Ravalement de facade inclus",
        "Meilleures performances thermiques globales",
      ],
      cons: [
        "Cout eleve (2 a 3 fois plus que l'ITI)",
        "Modification de l'aspect exterieur",
        "Echafaudage necessaire",
        "Interdite en secteur classe ou protege parfois",
      ],
      avgPrice: "80 - 200 EUR/m2",
    },
    verdict: "L'ITE est la solution la plus performante car elle supprime les ponts thermiques et ne reduit pas la surface habitable. Elle est ideale lors d'un ravalement de facade. L'ITI est le choix pragmatique quand le budget est limite, quand la facade ne peut pas etre modifiee ou quand les travaux doivent etre faits piece par piece.",
    relatedServiceSlug: "isolation-thermique",
  },
  {
    slug: "climatisation-split-vs-monobloc",
    title: "Climatisation split vs monobloc",
    metaTitle: "Climatisation split ou monobloc : laquelle choisir ?",
    metaDescription: "Climatisation split ou monobloc ? Comparez les performances, le bruit, l'installation et les prix pour rafraichir votre logement efficacement.",
    option1: {
      name: "Climatisation split (unite interieure + exterieure)",
      pros: [
        "Performances elevees (SEER superieur a 5)",
        "Fonctionnement silencieux a l'interieur (20-30 dB)",
        "Mode chauffage reversible disponible",
        "Possibilite de multi-split (plusieurs pieces)",
        "Design discret et moderne",
      ],
      cons: [
        "Installation par un professionnel obligatoire",
        "Unite exterieure visible et parfois bruyante",
        "Cout d'installation plus eleve",
        "Autorisation copropriete parfois necessaire",
      ],
      avgPrice: "1 500 - 4 000 EUR",
    },
    option2: {
      name: "Climatisation monobloc (mobile ou fixe)",
      pros: [
        "Prix d'achat tres reduit",
        "Installation simple, sans travaux",
        "Deplacable d'une piece a l'autre (mobile)",
        "Pas de groupe exterieur",
        "Ideal pour une utilisation ponctuelle",
      ],
      cons: [
        "Performances energetiques inferieures",
        "Bruit important (50-65 dB pour les modeles mobiles)",
        "Gaine d'evacuation par la fenetre (perte de froid)",
        "Consommation electrique plus elevee",
      ],
      avgPrice: "200 - 1 200 EUR",
    },
    verdict: "Le split est le choix optimal pour une climatisation performante et quotidienne. Il est plus silencieux, plus efficace et plus economique a l'usage. Le monobloc mobile convient pour un usage ponctuel (quelques semaines par an) ou quand l'installation d'un split est impossible (location, copropriete refusant le groupe exterieur).",
    relatedServiceSlug: "installation-climatisation",
  },
  {
    slug: "peinture-acrylique-vs-glycero",
    title: "Peinture acrylique vs glycero",
    metaTitle: "Peinture acrylique ou glycero : laquelle choisir ?",
    metaDescription: "Peinture acrylique ou glycerophtalique ? Comparez la tenue, l'odeur, le sechage et les prix pour bien choisir votre peinture interieure.",
    option1: {
      name: "Peinture acrylique (a l'eau)",
      pros: [
        "Quasi inodore et peu de COV",
        "Sechage rapide (1 a 2 heures entre couches)",
        "Nettoyage des outils a l'eau",
        "Large gamme de finitions (mat, satin, brillant)",
        "Respectueuse de l'environnement",
      ],
      cons: [
        "Moins resistante aux chocs et a l'abrasion",
        "Moins couvrante sur certains supports",
        "Tenue moindre en milieu tres humide",
        "Necessite un support bien prepare",
      ],
      avgPrice: "3 - 15 EUR/m2",
    },
    option2: {
      name: "Peinture glycerophtalique (a l'huile)",
      pros: [
        "Tres resistante aux chocs et a l'abrasion",
        "Excellent pouvoir couvrant",
        "Finition lisse et tendue",
        "Lessivable et resistante a l'humidite",
        "Ideale pour les boiseries et les metaux",
      ],
      cons: [
        "Odeur forte et persistante pendant plusieurs jours",
        "Taux de COV eleve (reglemente)",
        "Sechage long (6 a 12 heures entre couches)",
        "Nettoyage au white-spirit (solvant)",
      ],
      avgPrice: "5 - 18 EUR/m2",
    },
    verdict: "L'acrylique est aujourd'hui le choix standard pour 90% des travaux de peinture interieure : murs, plafonds et meme boiseries grace aux formulations modernes. La glycero reste pertinente pour les pieces tres humides (salle de bain sans VMC), les supports tres sollicites (portes, encadrements) et les boiseries exterieures. La tendance est clairement a l'acrylique pour des raisons sanitaires et environnementales.",
    relatedServiceSlug: "peinture-interieure",
  },
  {
    slug: "tuile-beton-vs-terre-cuite",
    title: "Tuile beton vs tuile terre cuite",
    metaTitle: "Tuile beton ou terre cuite : quelle tuile pour votre toiture ?",
    metaDescription: "Tuile beton ou terre cuite ? Comparez la duree de vie, l'esthetique, le poids et les prix pour choisir la bonne tuile pour votre toit.",
    option1: {
      name: "Tuile beton",
      pros: [
        "Prix 20 a 30% inferieur a la terre cuite",
        "Bonne resistance au gel",
        "Large choix de formes et de coloris",
        "Production plus ecologique (cuisson a basse temperature)",
        "Legere et facile a poser",
      ],
      cons: [
        "Duree de vie inferieure (30-50 ans vs 80-100 ans)",
        "Esthetique moins noble",
        "Mousse et lichen se developpent plus facilement",
        "Coloris qui peut s'alterer avec le temps",
      ],
      avgPrice: "15 - 35 EUR/m2",
    },
    option2: {
      name: "Tuile terre cuite",
      pros: [
        "Duree de vie exceptionnelle (80-100 ans)",
        "Esthetique traditionnelle et noble",
        "Coloris stable dans le temps (teinte dans la masse)",
        "Excellente resistance aux intemperies",
        "Patrimoine architectural francais",
      ],
      cons: [
        "Prix plus eleve",
        "Poids plus important (necessite charpente adaptee)",
        "Choix de formes plus restreint selon les regions",
        "Plus fragile aux chocs ponctuels",
      ],
      avgPrice: "25 - 60 EUR/m2",
    },
    verdict: "La tuile terre cuite est le choix patrimonial par excellence : sa duree de vie de 80 a 100 ans en fait un investissement perenne. La tuile beton est une alternative economique valable pour les constructions neuves a budget maitrise, mais sa duree de vie plus courte implique un remplacement plus frequent. Dans les zones soumises au PLU, le materiau peut etre impose.",
    relatedServiceSlug: "couverture-toiture",
  },
  {
    slug: "placo-standard-vs-hydrofuge",
    title: "Placo standard vs hydrofuge",
    metaTitle: "Placo standard ou hydrofuge : lequel utiliser ?",
    metaDescription: "Placo standard (BA13) ou hydrofuge (plaque verte) ? Decouvrez quand utiliser chaque type de plaque de platre et leurs differences de prix.",
    option1: {
      name: "Placo standard (BA13 blanc)",
      pros: [
        "Prix le plus bas du marche",
        "Convient a toutes les pieces seches",
        "Facile a couper et a poser",
        "Bonne surface pour peinture et papier peint",
        "Disponible partout",
      ],
      cons: [
        "Se degrade en milieu humide",
        "Gonfle et moisit au contact prolonge de l'eau",
        "Interdit dans les salles de bain et cuisines",
        "Resistance mecanique limitee",
      ],
      avgPrice: "3 - 6 EUR/m2",
    },
    option2: {
      name: "Placo hydrofuge (plaque verte H1)",
      pros: [
        "Resiste a l'humidite ambiante",
        "Obligatoire dans les pieces humides",
        "Meme facilite de pose que le standard",
        "Traitement anti-moisissure integre",
        "Supporte le carrelage colle",
      ],
      cons: [
        "Prix plus eleve que le standard",
        "Ne resiste pas a l'immersion ou au contact direct de l'eau",
        "Necessite tout de meme une bonne ventilation",
        "Choix de coloris et finitions plus limite",
      ],
      avgPrice: "5 - 10 EUR/m2",
    },
    verdict: "Le placo standard convient a toutes les pieces seches (chambres, salon, couloirs). Le placo hydrofuge est obligatoire dans les pieces humides (salle de bain, WC, cuisine, buanderie). Le surcout est modeste (2 a 4 EUR/m2) et la protection contre l'humidite est essentielle pour la durabilite de vos amenagements.",
    relatedServiceSlug: "plaquisterie-cloisons",
  },
  {
    slug: "serrure-multipoint-vs-monopoint",
    title: "Serrure multipoint vs monopoint",
    metaTitle: "Serrure multipoint ou monopoint : laquelle choisir ?",
    metaDescription: "Serrure multipoint ou monopoint ? Comparez la securite, le prix et l'installation pour bien proteger votre porte d'entree.",
    option1: {
      name: "Serrure multipoint (3 a 7 points)",
      pros: [
        "Securite renforcee (certification A2P)",
        "3 a 7 points de verrouillage repartis sur la porte",
        "Tres dissuasive contre l'effraction",
        "Obligatoire pour les portes certifiees anti-effraction",
        "Possibilite de certification A2P 1, 2 ou 3 etoiles",
      ],
      cons: [
        "Prix d'achat et de pose plus eleve",
        "Remplacement plus complexe et couteux",
        "Mecanisme plus fragile si mal entretenu",
        "Depannage en urgence plus couteux",
      ],
      avgPrice: "150 - 600 EUR",
    },
    option2: {
      name: "Serrure monopoint",
      pros: [
        "Prix d'achat tres accessible",
        "Installation et remplacement simples",
        "Depannage rapide et peu couteux",
        "Convient aux portes interieures",
        "Large choix de modeles disponibles",
      ],
      cons: [
        "Un seul point de verrouillage",
        "Securite limitee contre l'effraction",
        "Non certifiable A2P pour les portes d'entree",
        "Insuffisante pour une porte d'entree",
      ],
      avgPrice: "30 - 150 EUR",
    },
    verdict: "La serrure multipoint est indispensable pour toute porte d'entree. Un modele 3 points certifie A2P offre une securite suffisante pour la plupart des logements. Les modeles 5 ou 7 points sont recommandes pour les rez-de-chaussee et les zones a risque. La serrure monopoint est reservee aux portes interieures et aux portes de service.",
    relatedServiceSlug: "depannage-serrurerie",
  },
  {
    slug: "chaudiere-gaz-vs-granules",
    title: "Chaudiere gaz vs chaudiere a granules",
    metaTitle: "Chaudiere gaz ou granules : quel chauffage choisir ?",
    metaDescription: "Chaudiere gaz ou chaudiere a granules de bois ? Comparez les couts, le rendement, l'ecologie et les aides pour bien choisir votre chauffage.",
    option1: {
      name: "Chaudiere gaz a condensation",
      pros: [
        "Cout d'installation modere",
        "Encombrement reduit",
        "Rendement eleve (jusqu'a 109%)",
        "Alimentation automatique (reseau de gaz)",
        "Technologie eprouvee et fiable",
      ],
      cons: [
        "Energie fossile (impact environnemental)",
        "Prix du gaz volatil et en hausse",
        "Interdite dans les constructions neuves depuis 2022",
        "Raccordement au reseau de gaz necessaire",
      ],
      avgPrice: "3 000 - 7 000 EUR",
    },
    option2: {
      name: "Chaudiere a granules (pellets)",
      pros: [
        "Energie renouvelable et locale",
        "Prix du granule stable et competitif",
        "Eligible a toutes les aides (MaPrimeRenov, CEE)",
        "Empreinte carbone quasi neutre",
        "Excellent rendement (90-95%)",
      ],
      cons: [
        "Cout d'installation eleve",
        "Encombrement important (silo de stockage)",
        "Entretien plus frequent (cendres, ramonage)",
        "Bruit de la vis sans fin d'alimentation",
      ],
      avgPrice: "10 000 - 20 000 EUR",
    },
    verdict: "La chaudiere a granules est le choix d'avenir : energie renouvelable, prix stable, aides massives qui reduisent fortement l'investissement. Elle convient idealement aux maisons individuelles avec de l'espace pour le silo. La chaudiere gaz reste pertinente en remplacement dans les immeubles collectifs ou les maisons raccordees au gaz, mais son avenir est compromis par la reglementation environnementale.",
    relatedServiceSlug: "depannage-chauffage",
  },
  {
    slug: "panneau-solaire-monocristallin-vs-polycristallin",
    title: "Panneau solaire monocristallin vs polycristallin",
    metaTitle: "Panneau solaire monocristallin ou polycristallin : lequel choisir ?",
    metaDescription: "Monocristallin ou polycristallin ? Comparez le rendement, le prix et la duree de vie des deux types de panneaux solaires photovoltaiques.",
    option1: {
      name: "Panneau monocristallin",
      pros: [
        "Rendement superieur (18 a 24%)",
        "Meilleure performance en faible luminosite",
        "Esthetique plus homogene (noir uniforme)",
        "Moins de surface necessaire a puissance egale",
        "Duree de vie de 30 a 40 ans",
      ],
      cons: [
        "Prix legerement plus eleve",
        "Fabrication plus energivore",
        "Sensibilite aux hautes temperatures",
        "Perte de rendement par temps tres chaud",
      ],
      avgPrice: "200 - 350 EUR par panneau",
    },
    option2: {
      name: "Panneau polycristallin",
      pros: [
        "Prix d'achat inferieur",
        "Fabrication moins energivore",
        "Bonne performance a haute temperature",
        "Technologie mature et eprouvee",
      ],
      cons: [
        "Rendement inferieur (15 a 18%)",
        "Plus de surface necessaire a puissance egale",
        "Esthetique moins homogene (reflets bleutes)",
        "Moins performant par faible luminosite",
        "En voie de disparition sur le marche residentiel",
      ],
      avgPrice: "150 - 250 EUR par panneau",
    },
    verdict: "Le monocristallin domine desormais le marche residentiel grace a son meilleur rendement et son esthetique superieure. L'ecart de prix s'est considerablement reduit ces dernieres annees. Le polycristallin reste pertinent pour les grandes installations au sol ou le budget est prioritaire et l'espace n'est pas limite. Pour une toiture residentielle, le monocristallin est le choix recommande.",
    relatedServiceSlug: "nettoyage-panneaux-solaires",
  },
  {
    slug: "portail-aluminium-vs-pvc",
    title: "Portail aluminium vs PVC",
    metaTitle: "Portail aluminium ou PVC : quel materiau choisir ?",
    metaDescription: "Portail aluminium ou PVC ? Comparez la solidite, l'esthetique, l'entretien et les prix pour choisir le bon materiau de portail.",
    option1: {
      name: "Portail aluminium",
      pros: [
        "Leger et tres resistant a la corrosion",
        "Large choix de coloris et de styles",
        "Entretien minimal (nettoyage a l'eau)",
        "Duree de vie superieure a 30 ans",
        "Compatible avec toutes les motorisations",
      ],
      cons: [
        "Prix plus eleve que le PVC",
        "Moins isolant thermiquement",
        "Bosses et rayures difficiles a reparer",
        "Design parfois froid ou industriel",
      ],
      avgPrice: "1 500 - 4 000 EUR",
    },
    option2: {
      name: "Portail PVC",
      pros: [
        "Prix le plus accessible du marche",
        "Entretien tres facile",
        "Bonne resistance aux intemperies",
        "Ne rouille pas et ne pourrit pas",
        "Bon isolant thermique",
      ],
      cons: [
        "Choix de coloris limite (surtout blanc)",
        "Moins resistant aux chocs",
        "Peut jaunir avec le temps sous l'effet du soleil",
        "Aspect moins haut de gamme",
        "Duree de vie inferieure a l'aluminium",
      ],
      avgPrice: "600 - 2 000 EUR",
    },
    verdict: "L'aluminium est le choix haut de gamme : design moderne, coloris au choix, longevite et solidite. Le PVC est le choix budget : accessible, sans entretien et suffisant pour un usage residentiel standard. Pour un portail motorise de grande largeur, l'aluminium est preferable car sa rigidite garantit un fonctionnement optimal de l'automatisme.",
    relatedServiceSlug: "depannage-portail-electrique",
  },
  {
    slug: "laine-de-verre-vs-laine-de-roche",
    title: "Laine de verre vs laine de roche",
    metaTitle: "Laine de verre ou laine de roche : quel isolant choisir ?",
    metaDescription: "Laine de verre ou laine de roche ? Comparez les performances thermiques, acoustiques, le prix et la mise en oeuvre de ces deux isolants mineraux.",
    option1: {
      name: "Laine de verre",
      pros: [
        "Prix le plus bas des isolants mineraux",
        "Tres bonne performance thermique (lambda 0,030-0,040)",
        "Legere et facile a poser",
        "Incombustible (classee A1 au feu)",
        "Large gamme d'epaisseurs et conditionnements",
      ],
      cons: [
        "Isolation phonique inferieure a la laine de roche",
        "Sensible a l'humidite (perd ses proprietes)",
        "Irritante a la pose (port de protections obligatoire)",
        "Tassement possible dans le temps",
      ],
      avgPrice: "3 - 10 EUR/m2",
    },
    option2: {
      name: "Laine de roche",
      pros: [
        "Excellente isolation acoustique",
        "Meilleure resistance au feu (point de fusion 1000 degres)",
        "Plus dense, meilleur comportement a l'humidite",
        "Bon dephasage thermique (confort d'ete)",
        "Tassement moindre dans le temps",
      ],
      cons: [
        "Prix 20 a 40% superieur a la laine de verre",
        "Plus lourde (contrainte pour les plafonds)",
        "Egalement irritante a la pose",
        "Performance thermique legerement inferieure a epaisseur egale",
      ],
      avgPrice: "5 - 15 EUR/m2",
    },
    verdict: "La laine de verre est le choix le plus economique pour l'isolation thermique des combles et des murs, surtout quand le budget est serre. La laine de roche est superieure pour l'isolation phonique (cloisons mitoyennes, planchers), la resistance au feu et le confort d'ete. Dans les combles perdus, la laine de verre soufflee est le meilleur rapport qualite-prix. Pour les cloisons phoniques, la laine de roche s'impose.",
    relatedServiceSlug: "isolation-thermique",
  },
  {
    slug: "combles-amenages-vs-surelevation",
    title: "Combles amenages vs surelevation",
    metaTitle: "Amenagement de combles ou surelevation : que choisir ?",
    metaDescription: "Amenager les combles ou surelever la maison ? Comparez les prix, les contraintes et les avantages pour gagner de la surface habitable.",
    option1: {
      name: "Amenagement de combles",
      pros: [
        "Cout nettement inferieur a la surelevation",
        "Travaux moins lourds et moins longs",
        "Pas de modification de la structure principale",
        "Declaration prealable souvent suffisante",
        "Travaux realisables en logement occupe",
      ],
      cons: [
        "Possible uniquement si les combles sont amenageables",
        "Hauteur sous plafond limitee par la pente du toit",
        "Surface utile reduite par les rampants",
        "Modification de charpente parfois necessaire",
      ],
      avgPrice: "500 - 1 500 EUR/m2",
    },
    option2: {
      name: "Surelevation de maison",
      pros: [
        "Gain de surface maximise (murs droits pleine hauteur)",
        "Possible meme sans combles amenageables",
        "Nouvelle toiture neuve et isolee",
        "Augmentation significative de la valeur du bien",
        "Possibilite de modifier totalement l'amenagement",
      ],
      cons: [
        "Cout tres eleve (2 a 3 fois plus que l'amenagement)",
        "Travaux lourds et longs (3 a 6 mois)",
        "Permis de construire obligatoire",
        "Verification de la capacite portante des fondations",
        "Logement potentiellement inhabitable pendant les travaux",
      ],
      avgPrice: "1 500 - 3 000 EUR/m2",
    },
    verdict: "L'amenagement de combles est la solution a privilegier quand les combles sont amenageables (hauteur sous faitage suffisante, charpente traditionnelle). C'est 2 a 3 fois moins cher et beaucoup moins contraignant. La surelevation est la seule option quand les combles ne sont pas amenageables ou quand on souhaite un etage complet avec murs droits et pleine hauteur sous plafond.",
    relatedServiceSlug: "amenagement-combles",
  },
];

export function getComparatifBySlug(slug: string): Comparatif | undefined {
  return comparatifs.find((c) => c.slug === slug);
}
