export interface Service {
  slug: string;
  name: string;
  icon: string;
  shortDescription: string;
  description: string;
  keywords: string[];
  priceRange: string;
}

export const services: Service[] = [
  {
    slug: "reparation-volets-roulants",
    name: "Réparation de volets roulants",
    icon: "Blinds",
    shortDescription: "Volet bloqué, lame cassée, moteur en panne ? Nos artisans interviennent rapidement.",
    description: "Votre volet roulant est bloqué, une lame est cassée ou le moteur ne répond plus ? Nos artisans qualifiés interviennent rapidement pour diagnostiquer et réparer tous types de volets roulants : manuels, électriques ou solaires. Recevez jusqu'à 3 devis gratuits et sans engagement.",
    keywords: ["volet roulant", "réparation volet", "volet bloqué", "moteur volet"],
    priceRange: "80 - 400 €",
  },
  {
    slug: "recherche-fuite-eau",
    name: "Recherche de fuite d'eau",
    icon: "Droplets",
    shortDescription: "Fuite d'eau invisible ? Détection non destructive par nos experts.",
    description: "Une fuite d'eau peut causer des dégâts considérables si elle n'est pas détectée à temps. Nos artisans utilisent des techniques de détection non destructives (caméra thermique, gaz traceur) pour localiser précisément la fuite sans endommager vos murs ou sols.",
    keywords: ["fuite eau", "recherche fuite", "détection fuite", "dégât des eaux"],
    priceRange: "150 - 500 €",
  },
  {
    slug: "debarras-maison",
    name: "Débarras de maison",
    icon: "Home",
    shortDescription: "Débarras complet de maison, appartement, cave ou grenier.",
    description: "Besoin de vider une maison, un appartement, une cave ou un grenier ? Nos professionnels du débarras prennent en charge le tri, l'enlèvement et le recyclage de vos encombrants. Service rapide et respectueux de l'environnement.",
    keywords: ["débarras", "vide maison", "enlèvement encombrants", "débarras cave"],
    priceRange: "200 - 2000 €",
  },
  {
    slug: "traitement-nuisibles",
    name: "Traitement nuisibles",
    icon: "Bug",
    shortDescription: "Rats, punaises de lit, cafards ? Intervention rapide et discrète.",
    description: "Rats, souris, punaises de lit, cafards, guêpes... Nos experts en dératisation et désinsectisation interviennent rapidement et discrètement pour éliminer tous types de nuisibles. Traitement professionnel avec garantie de résultat.",
    keywords: ["nuisibles", "dératisation", "punaises de lit", "désinsectisation", "cafards"],
    priceRange: "100 - 600 €",
  },
  {
    slug: "entretien-pompe-chaleur",
    name: "Entretien pompe à chaleur",
    icon: "Thermometer",
    shortDescription: "Entretien annuel obligatoire de votre pompe à chaleur par un pro certifié.",
    description: "L'entretien annuel de votre pompe à chaleur est obligatoire et essentiel pour maintenir ses performances. Nos techniciens certifiés vérifient le fluide frigorigène, nettoient les filtres et contrôlent l'ensemble du système.",
    keywords: ["pompe à chaleur", "entretien PAC", "maintenance chauffage", "fluide frigorigène"],
    priceRange: "150 - 300 €",
  },
  {
    slug: "nettoyage-panneaux-solaires",
    name: "Nettoyage panneaux solaires",
    icon: "Sun",
    shortDescription: "Nettoyage professionnel pour optimiser le rendement de vos panneaux.",
    description: "Des panneaux solaires sales peuvent perdre jusqu'à 30% de leur rendement. Nos professionnels utilisent des techniques de nettoyage adaptées (eau pure, brosses douces) pour redonner à vos panneaux toute leur efficacité sans les endommager.",
    keywords: ["panneaux solaires", "nettoyage photovoltaïque", "rendement solaire", "entretien panneaux"],
    priceRange: "100 - 300 €",
  },
  {
    slug: "depannage-portail-electrique",
    name: "Dépannage portail électrique",
    icon: "DoorOpen",
    shortDescription: "Portail bloqué ou en panne ? Dépannage rapide par un spécialiste.",
    description: "Votre portail électrique ne s'ouvre plus, fait du bruit ou fonctionne de manière erratique ? Nos techniciens spécialisés diagnostiquent et réparent tous types de portails : coulissants, battants, automatiques.",
    keywords: ["portail électrique", "dépannage portail", "motorisation portail", "portail bloqué"],
    priceRange: "100 - 500 €",
  },
  {
    slug: "ramonage-cheminee",
    name: "Ramonage cheminée",
    icon: "Flame",
    shortDescription: "Ramonage obligatoire de cheminée et conduit par un professionnel certifié.",
    description: "Le ramonage de votre cheminée est une obligation légale (1 à 2 fois par an selon les régions). Nos ramoneurs certifiés nettoient vos conduits pour prévenir les risques d'incendie et d'intoxication au monoxyde de carbone. Certificat de ramonage fourni.",
    keywords: ["ramonage", "cheminée", "conduit fumée", "ramoneur certifié"],
    priceRange: "50 - 120 €",
  },
  {
    slug: "plomberie-urgente",
    name: "Plomberie urgente",
    icon: "Wrench",
    shortDescription: "Fuite, canalisation bouchée, panne de chauffe-eau ? Intervention urgente.",
    description: "Fuite d'eau importante, canalisation bouchée, panne de chauffe-eau, WC hors service... Nos plombiers interviennent en urgence pour résoudre vos problèmes de plomberie. Disponibilité rapide et devis transparent.",
    keywords: ["plombier", "urgence plomberie", "fuite eau", "canalisation bouchée", "chauffe-eau"],
    priceRange: "80 - 500 €",
  },
  {
    slug: "depannage-chauffage",
    name: "Dépannage chauffage",
    icon: "ThermometerSun",
    shortDescription: "Panne de chauffage ? Dépannage rapide chaudière et radiateurs.",
    description: "Votre chaudière est en panne, vos radiateurs ne chauffent plus ou votre système de chauffage fait du bruit ? Nos chauffagistes qualifiés interviennent rapidement pour diagnostiquer et réparer votre installation.",
    keywords: ["dépannage chauffage", "panne chaudière", "réparation radiateur", "chauffagiste"],
    priceRange: "100 - 500 €",
  },
  {
    slug: "depannage-electrique",
    name: "Dépannage électrique",
    icon: "Zap",
    shortDescription: "Panne de courant, court-circuit ou tableau électrique défaillant ? Nos électriciens interviennent vite.",
    description: "Une panne électrique peut survenir à tout moment et paralyser votre quotidien. Nos électriciens qualifiés diagnostiquent et réparent rapidement tout type de problème : court-circuit, disjoncteur qui saute, prise défectueuse ou tableau électrique endommagé. Intervention sécurisée et conforme aux normes en vigueur.",
    keywords: ["panne electrique", "electricien", "tableau electrique", "court-circuit"],
    priceRange: "80 - 400 €",
  },
  {
    slug: "depannage-serrurerie",
    name: "Dépannage serrurerie",
    icon: "Lock",
    shortDescription: "Porte claquée, serrure bloquée ou clé cassée ? Un serrurier intervient en urgence.",
    description: "Vous êtes enfermé dehors, votre serrure est bloquée ou votre clé s'est cassée dans la porte ? Nos serruriers professionnels interviennent rapidement pour toute ouverture de porte, remplacement de serrure ou mise en sécurité de votre domicile. Devis clair et sans surprise avant toute intervention.",
    keywords: ["serrurier", "porte claquée", "serrure bloquée", "ouverture de porte"],
    priceRange: "80 - 350 €",
  },
  {
    slug: "isolation-thermique",
    name: "Isolation thermique",
    icon: "ShieldCheck",
    shortDescription: "Améliorez le confort de votre logement et réduisez vos factures grâce à une isolation performante.",
    description: "Une bonne isolation thermique est la clé pour réduire vos factures d'énergie et améliorer le confort de votre habitat. Nos artisans certifiés RGE réalisent l'isolation de vos combles, murs et planchers avec des matériaux de qualité. Profitez des aides financières disponibles (MaPrimeRénov', CEE) pour alléger le coût de vos travaux.",
    keywords: ["isolation", "isolation thermique", "combles", "murs"],
    priceRange: "30 - 100 € /m²",
  },
  {
    slug: "installation-climatisation",
    name: "Installation climatisation",
    icon: "Wind",
    shortDescription: "Installation de climatisation réversible ou split par un professionnel certifié.",
    description: "Gardez votre intérieur frais en été et tempéré en hiver grâce à une climatisation réversible performante. Nos installateurs certifiés prennent en charge l'étude, la pose et la mise en service de votre système de climatisation : split, multi-split ou pompe à chaleur air-air. Un confort optimal toute l'année avec un équipement adapté à votre logement.",
    keywords: ["climatisation", "clim", "installation clim", "pompe à chaleur air-air"],
    priceRange: "800 - 3000 €",
  },
  {
    slug: "peinture-interieure",
    name: "Peinture intérieure",
    icon: "Paintbrush",
    shortDescription: "Rafraîchissez vos murs et plafonds avec un peintre professionnel qualifié.",
    description: "Envie de redonner un coup de neuf à votre intérieur ? Nos peintres professionnels réalisent tous vos travaux de peinture : murs, plafonds, boiseries et finitions soignées. Préparation des supports, choix des peintures adaptées et application dans les règles de l'art pour un résultat impeccable et durable.",
    keywords: ["peinture", "peintre", "peinture intérieure", "ravalement"],
    priceRange: "20 - 45 € /m²",
  },
  // --- 10 nouveaux services - Expansion SEO ---
  {
    slug: "installation-chauffe-eau",
    name: "Installation chauffe-eau",
    icon: "Flame",
    shortDescription: "Remplacement ou installation de chauffe-eau électrique, gaz ou thermodynamique par un plombier qualifié.",
    description: "Votre ballon d'eau chaude est en panne, fuit ou ne chauffe plus ? Nos plombiers chauffagistes installent et remplacent tous types de chauffe-eau : électrique (cumulus), gaz, thermodynamique ou solaire. Profitez d'un diagnostic gratuit et de conseils personnalisés pour choisir l'équipement le plus adapté à votre consommation et à votre budget. Installation conforme aux normes en vigueur avec garantie constructeur.",
    keywords: ["chauffe-eau", "ballon eau chaude", "cumulus", "installation chauffe-eau", "remplacement cumulus"],
    priceRange: "300 - 1500 €",
  },
  {
    slug: "renovation-salle-de-bain",
    name: "Rénovation salle de bain",
    icon: "Bath",
    shortDescription: "Rénovation complète de salle de bain : douche italienne, baignoire, carrelage et plomberie.",
    description: "Transformez votre salle de bain en un espace moderne et fonctionnel. Nos artisans prennent en charge l'intégralité de votre projet : dépose de l'ancienne salle de bain, plomberie, électricité, pose de carrelage, installation de douche à l'italienne ou baignoire, meuble vasque et accessoires. Nous réalisons également les mises aux normes PMR pour l'accessibilité des personnes à mobilité réduite.",
    keywords: ["renovation salle de bain", "douche italienne", "salle d'eau", "plomberie salle de bain", "baignoire"],
    priceRange: "3000 - 15000 €",
  },
  {
    slug: "pose-carrelage",
    name: "Pose de carrelage",
    icon: "Grid3x3",
    shortDescription: "Pose de carrelage sol et mur par un carreleur professionnel : grès cérame, faïence, mosaïque.",
    description: "Faites poser votre carrelage par un carreleur expérimenté pour un résultat impeccable et durable. Nos professionnels maîtrisent toutes les techniques de pose (collée, scellée, sur plots) et tous les formats : carrelage grand format, mosaïque, faïence murale, grès cérame, imitation parquet ou pierre naturelle. Préparation du support, découpes précises et joints soignés pour une finition parfaite.",
    keywords: ["carrelage", "pose carrelage", "faience", "carreleur", "gres cerame"],
    priceRange: "30 - 80 € /m²",
  },
  {
    slug: "installation-vmc",
    name: "Installation VMC",
    icon: "Fan",
    shortDescription: "Installation de VMC simple flux ou double flux pour un air sain et une maison sans humidité.",
    description: "Une ventilation performante est essentielle pour la qualité de l'air intérieur et la prévention de l'humidité. Nos techniciens installent et remplacent tous types de VMC : simple flux autoréglable, hygroréglable type A ou B, et double flux haut rendement avec récupération de chaleur. Nous assurons le dimensionnement adapté à votre logement, la pose des bouches d'extraction et d'insufflation, et la mise en service complète.",
    keywords: ["VMC", "ventilation", "VMC double flux", "qualite air interieur", "VMC hygroreglable"],
    priceRange: "500 - 3000 €",
  },
  {
    slug: "ravalement-facade",
    name: "Ravalement de façade",
    icon: "Building2",
    shortDescription: "Ravalement et rénovation de façade : nettoyage, enduit, peinture et isolation par l'extérieur.",
    description: "Le ravalement de façade est une obligation légale tous les 10 ans dans de nombreuses communes. Nos façadiers professionnels réalisent le nettoyage haute pression, la réparation des fissures, l'application d'enduit (monocouche, traditionnel, à la chaux) et la peinture de façade. Profitez-en pour réaliser une isolation thermique par l'extérieur (ITE) et bénéficier des aides MaPrimeRénov' et CEE.",
    keywords: ["ravalement", "facade", "crepi", "enduit facade", "isolation exterieure"],
    priceRange: "30 - 100 € /m²",
  },
  {
    slug: "pose-fenetres",
    name: "Pose de fenêtres",
    icon: "SquareStack",
    shortDescription: "Remplacement et pose de fenêtres double ou triple vitrage en PVC, aluminium ou bois.",
    description: "Remplacez vos anciennes fenêtres pour améliorer l'isolation thermique et phonique de votre logement. Nos menuisiers posent tous types de fenêtres : PVC (meilleur rapport qualité-prix), aluminium (design contemporain) et bois (charme authentique), en double ou triple vitrage. Chaque installation inclut la dépose de l'ancien cadre, la pose en rénovation ou en neuf, les finitions intérieures et extérieures, et le réglage des ouvrants. Éligible aux aides MaPrimeRénov'.",
    keywords: ["fenetre", "double vitrage", "pose fenetre", "menuiserie", "triple vitrage"],
    priceRange: "300 - 1200 € /fenêtre",
  },
  {
    slug: "couverture-toiture",
    name: "Couverture et toiture",
    icon: "Home",
    shortDescription: "Réparation, rénovation et entretien de toiture : tuiles, ardoises, zinc et étanchéité.",
    description: "Votre toiture fuit, des tuiles sont cassées ou votre couverture est vieillissante ? Nos couvreurs professionnels interviennent pour tous types de travaux : réparation de fuites, remplacement de tuiles ou ardoises, réfection complète de couverture, pose de gouttières et zinguerie, traitement hydrofuge et démoussage. Nous travaillons tous les matériaux : tuile terre cuite, tuile béton, ardoise naturelle, zinc et bac acier.",
    keywords: ["toiture", "couvreur", "reparation toit", "tuiles", "ardoises", "zinguerie"],
    priceRange: "50 - 150 € /m²",
  },
  {
    slug: "terrassement",
    name: "Terrassement",
    icon: "Mountain",
    shortDescription: "Terrassement, excavation et préparation de terrain pour construction, piscine ou aménagement.",
    description: "Le terrassement est la première étape indispensable de tout projet de construction ou d'aménagement extérieur. Nos terrassiers professionnels réalisent le décapage, le nivellement, le creusement de fondations, les tranchées pour réseaux (VRD), l'excavation de piscine et la viabilisation de terrain. Nous disposons d'engins adaptés à chaque chantier : mini-pelle, pelleteuse, compacteur. Évacuation des terres et remblaiement inclus sur devis.",
    keywords: ["terrassement", "excavation", "fondations", "VRD", "viabilisation"],
    priceRange: "25 - 60 € /m³",
  },
  {
    slug: "amenagement-combles",
    name: "Aménagement de combles",
    icon: "Warehouse",
    shortDescription: "Aménagement et isolation de combles pour créer de nouveaux espaces de vie sous votre toit.",
    description: "Gagnez des mètres carrés habitables en aménageant vos combles perdus. Nos artisans prennent en charge l'ensemble du projet : étude de faisabilité et de structure, renforcement de la charpente si nécessaire, isolation performante (laine de verre, laine de roche, ouate de cellulose), pose de fenêtres de toit type Velux, création de cloisons, électricité, plomberie et finitions. Un projet d'aménagement de combles peut augmenter la valeur de votre bien de 20 à 30%.",
    keywords: ["combles", "amenagement combles", "isolation combles", "surelevation", "velux"],
    priceRange: "500 - 1500 € /m²",
  },
  {
    slug: "plaquisterie-cloisons",
    name: "Plaquisterie et cloisons",
    icon: "Layers",
    shortDescription: "Pose de placo, cloisons sèches, faux plafonds et doublage isolant par un plaquiste qualifié.",
    description: "Nos plaquistes professionnels réalisent tous vos travaux de second œuvre : pose de plaques de plâtre (BA13, BA15), montage de cloisons de distribution ou de séparation, création de faux plafonds (suspendus ou autoportants), doublage isolant des murs et habillage de gaines techniques. Nous utilisons des plaques adaptées à chaque pièce : standard, hydrofuge (salle de bain), coupe-feu, ou phonique pour une isolation acoustique renforcée.",
    keywords: ["placo", "plaquiste", "cloison", "faux plafond", "BA13", "cloison seche"],
    priceRange: "25 - 60 € /m²",
  },
];

export function getServiceBySlug(slug: string): Service | undefined {
  return services.find((s) => s.slug === slug);
}
